io:
	gfortran -g -Wall io.f90

calculation:
	gfortran -g -Wall calculation.f90

data_type:
	gfortran -g -Wall data_type.f90

loop:
	gfortran -g -Wall loop.f90

global:
	gfortran -g -Wall global.f90

pointer:
	gfortran -g -Wall pointer.f90
