cc=clang++
## cc=g++
all: friend_class

const:
	$(cc) -g -Wall const.cpp

pointer:
	$(cc) -g -Wall pointer_function.cpp

class_demo:
	$(cc) -g -Wall class_demo.cpp
class_constructor_destructor:
	$(cc) -g -Wall class_constructor_destructor.cpp
class_overload_operator:
	$(cc) -g -Wall class_overload_operator.cpp

friend_function:
	$(cc) -g -Wall friend_function.cpp
friend_class:
	$(cc) -g -Wall friend_class.cpp

clean:
	rm a.out
