cc=clang++
## cc=g++
all: class_assignment

const:
	$(cc) -g -Wall const.cpp

pointer:
	$(cc) -g -Wall pointer_function.cpp

class_demo:
	$(cc) -g -Wall class_demo.cpp
class_constructor_destructor:
	$(cc) -g -Wall class_constructor_destructor.cpp
class_overload_operator:
	$(cc) -g -Wall class_overload_operator.cpp

friend_function:
	$(cc) -g -Wall friend_function.cpp
friend_class:
	$(cc) -g -Wall friend_class.cpp

inheritance_constructor:
	$(cc) -g -Wall inheritance_constructor.cpp
inheritance_destructor:
	$(cc) -g -Wall inheritance_destructor.cpp

class_assignment:
	$(cc) -g -Wall class_assignment.cpp

scope_class:
	$(cc) -g -Wall scope_class.cpp
scope_class2:
	$(cc) -g -Wall scope_class2.cpp
scope_class_virtual:
	$(cc) -g -Wall scope_class_virtual.cpp
scope_class_virtual_constructor:
	$(cc) -g -Wall scope_class_virtual_constructor.cpp

clean:
	rm a.out
