# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi
export PS1="[\t \u@\H:\W]\$ "
export LC_CTYPE="en_US.UTF-8"
export LC="C"

## bash use emacs by default, change it to vi
set -o vi

export PATH=$PATH:/sbin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:${HOME}/git/note/bin
export PATH=$PATH:${HOME}/bin

user=`whoami`
uname -a | grep Darwin 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  export os="mac"
  export ip=`ifconfig en0 | grep inet | grep -v inet6 | awk '{print $2}'`
else
  export os="linux"
  export ip=`ifconfig eth0 | grep inet | grep -v inet6 | awk '{print $2}'`
fi

ulimit -c unlimited

alias grep='grep --color=auto'
alias watch='watch -d -n 1'

alias ll="ls -l"
if [ "x$os" == "xmac" ]
then
  alias ls="ls -G"
else
  alias ls="ls --color=auto"
fi

export no_proxy="localhost,127.0.0.1,$ip"

[[ -f /usr/local/etc/profile.d/autojump.sh ]] && source /usr/local/etc/profile.d/autojump.sh # mac homebrew
[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && source ~/.autojump/etc/profile.d/autojump.sh # linux

# blade
export BLADE_AUTO_UPGRADE="no"
alias bb="blade build"
alias bt="blade test"
alias br="blade run"
test -s ~/bin/bladefunctions && . ~/bin/bladefunctions || true

## go
if [ "x$os" == "xlinux" ]; then
  export GOROOT="${HOME}/opt/go"
else
  export GOROOT="/usr/local/opt/go@1.13/libexec"
fi
export PATH="$PATH:$GOROOT/bin"
export GOPATH="${HOME}/go"
export PATH="$PATH:$GOPATH/bin"
export GO111MODULE=on
export GOPROXY="https://goproxy.io"

## java
export JAVA_HOME="$HOME/opt/jdk"
export PATH=$PATH:"$HOME/opt/jdk/bin"

# enterprise
if [ -f ~/.bashrc_enterprise ]; then
  source ~/.bashrc_enterprise
fi

# udf
## docker
if [ -f $HOME/git/docker/.dockerfunc ]
then
  source $HOME/git/docker/.dockerfunc
fi

