# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi
export PS1="[\u@\h:\W]\$ "
export LC_CTYPE="en_US.UTF-8"
export LC="C"

## bash use emacs by default, change it to vi
set -o vi

user=`whoami`
uname -a | grep Darwin 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
  os="mac"
else
  os="linux"
fi

export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:${HOME}/git/note/bin
export PATH=$PATH:${HOME}/bin
if [ -d /data/gcc-8.2.0/bin ]
then
  export PATH=/data/gcc-8.2.0/bin:$PATH
fi

ulimit -c unlimited

alias grep='grep --color=auto'
alias watch='watch -d -n 1'

alias ll="ls -l"
if [ "x$os" == "xmac" ]
then
  alias ls="ls -G"
else
  alias ls="ls --color=auto"
fi

# blade
export BLADE_AUTO_UPGRADE="no"
alias bb="blade build"
alias bt="blade test"
alias br="blade run"
test -s ~/bin/bladefunctions && . ~/bin/bladefunctions || true

## go
export GOPATH="${HOME}/opt/go"
export PATH="$PATH:$GOPATH/bin"
export GO111MODULE=on
export GOPROXY="https://goproxy.io"

## java
export JAVA_HOME="$HOME/opt/jdk"
export PATH="$HOME/opt/jdk/bin":$PATH

# enterprise
export PATH="$PATH:$HOME/.ft"

# udf
## docker
if [ -f $HOME/git/docker/.dockerfunc ]
then
  source $HOME/git/docker/.dockerfunc
fi

