yum install -y gcc gcc-c++ gcc-gfortran gdb
yum install -y sudo git git-svn
yum install -y unrar
yum remove -y evolution
yum install -y mutt
yum update -y firefox
yum install -y mysql mysql-server mysql-devel

## chrome

## project
## yum install -y libpcap libpcap-devel
## yum install -y wireshark ## no gui
## yum install -y wireshark-gnome

## octave
yum install -y hdf5-static ## will install hdf5, hdf5-static and hdf5-devel
yum install -y octave
